export const messages: string[] = [
  'Reticulando splines...',
  'Gerando diálogo inteligente...',
  'Troca de tempo e espaço...',
  'Girando violentamente ao redor do eixo y...',
  'Tokenizando a vida real...',
  'Dobrando a colher...',
  'Filtrando moral...',
  'Não pense em hipopótamos roxos...',
  'Precisamos de um novo fusível...',
  'Tenha um bom dia.',
  'Atualizando o Windows, seu PC reiniciará várias vezes. Relaxe e aproveite.',
  '640K deveriam ser suficientes para qualquer pessoa',
  'Os arquitetos ainda estão projetando',
  'Os bits estão se reproduzindo',
  'Estamos construindo os prédios o mais rápido possível',
  'Você prefere frango, bife ou tofu?',
  '(Não preste atenção no homem atrás da cortina)',
  '...e aproveite a música do elevador...',
  'Aguarde enquanto os pequenos elfos desenham seu mapa',
  'Não se preocupe - alguns bits tentaram escapar, mas nós os pegamos',
  'Gostaria de batatas fritas com isso?',
  'Verificando a constante gravitacional em sua localização...',
  'Vá em frente - segure a respiração!',
  '...pelo menos você não está na espera...',
  'Cante algo alto enquanto os outros olham',
  'Você não está mais no Kansas',
  'O servidor é alimentado por um limão e dois eletrodos.',
  'Aguarde enquanto uma grande empresa de software em Seattle toma conta do mundo',
  'Estamos testando sua paciência',
  'Como se você tivesse outra escolha',
  'Siga o coelho branco',
  'Por que você não pede um sanduíche?',
  'Enquanto o satélite se move para a posição',
  'Mantenha a calma e npm install',
  'Os bits estão fluindo lentamente hoje',
  "Cave no 'X' em busca de tesouro enterrado... ARRR!",
  'Ainda é mais rápido do que você poderia desenhá-lo',
  'Da última vez que tentei isso, o macaco não sobreviveu. Vamos esperar que funcione melhor desta vez.',
  'Eu deveria ter tomado um V8 esta manhã.',
  'Minha outra tela de carregamento é muito mais rápida.',
  'Testando em Timmy... Vamos precisar de outro Timmy.',
  'Reconfigurando o energymotron...',
  '(Inserir uma moeda)',
  'Já chegamos?',
  'Você emagreceu?',
  'Apenas conte até 10',
  'Por que tão sério?',
  'Não é você. Sou eu.',
  'Contando de volta do Infinito',
  'Não entre em pânico...',
  'Aumentando protótipos',
  'Não corra! Somos seus amigos!',
  'Você vem aqui com frequência?',
  'Aviso: Não se coloque fogo.',
  'Estamos fazendo um cookie para você.',
  'Criando campo de inversão de loop temporal',
  'Girando a roda da fortuna...',
  'Carregando o coelho encantado...',
  'Calculando a chance de sucesso',
  'Desculpe, Dave, não posso fazer isso.',
  'Procurando por troco exato',
  'Todos os seus navegadores da web nos pertencem',
  'Tudo o que eu realmente preciso é de um kilobit.',
  'Sinto que deveria estar carregando alguma coisa...',
  'O que você chama de 8 Hobbits? Um Hobbyte.',
  'Deveria ter usado uma linguagem compilada...',
  'Isso é o Windows?',
  'Ajustando o capacitor de fluxo...',
  'Aguarde até que a preguiça comece a se mover.',
  'Não quebre sua tela ainda!',
  'Juro que está quase pronto.',
  'Vamos fazer um minuto de atenção plena...',
  'Unicórnios estão no final desta estrada, eu prometo.',
  'Ouvindo o som de uma mão batendo...',
  'Mantendo todos os 1s e removendo todos os 0s...',
  'Colocando a cobertura no bolo. O bolo não é uma mentira...',
  'Limpando as teias de aranha...',
  "Garantindo que todos os i's tenham pontos...",
  'Precisamos de mais cristais de dilithium',
  'Para onde foram todos os internets',
  'Conectando o Tanque de Armazenamento de Neurotoxinas...',
  'Concedendo desejos...',
  'O tempo voa quando você está se divertindo.',
  'Pegue um café e volte em dez minutos...',
  'Girando o hamster...',
  '99 garrafas de cerveja na parede...',
  'Fique um pouco e ouça...',
  'Cuidado para não pisar no git-gui',
]
